# generated by datamodel-codegen:
#   filename:  rschema.json
#   timestamp: 2024-06-02T17:03:57+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel


class Zone(BaseModel):
    name: str


class Report(BaseModel):
    code: str
    visibility: str
    zone: Optional[Zone]


class Reports(BaseModel):
    has_more_pages: bool
    data: List[Report]


class ReportData(BaseModel):
    reports: Reports


class Data(BaseModel):
    reportData: ReportData


class Model(BaseModel):
    data: Data
